name = "cloudflare-icons"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build@0.7.5 && worker-build --release"

[vars]
WORKERS_RS_VERSION = "0.3.0"

[[r2_buckets]]
binding = "ICONS"
bucket_name = "cloudflare-icons"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-kv-namespace-preview-id"